# Docker compose for CI CD
version: '3'

volumes:
  jenkins-data-test:
    driver: local

services:
  sonarqube:
    image: sonarqube
    ports:
      - 9000:9000
  jenkins:
    image: jenkinsci/blueocean
    user : root
    volumes:
      - jenkins-data-test:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - $HOME:/home
    ports:
      - 8080:8080
    depends_on:
      - sonarqube
