node{
    stage("SCM checkout"){
        git url: 'https://github.com/sardaens/simple-java-maven-app.git', branch: 'master'
    }
    stage("Mvn package"){
    	def mavenHome = tool name: 'maven-3', type: 'maven'
    	def mavenCmd = "${mavenHome}/bin/mvn"

        sh '${mavenCmd} clean package'
    }

}
