node{
    stage("SCM checkout"){
        git url: 'https://github.com/sardaens/simple-java-maven-app.git', branch: 'master'
    }
    stage("Mvn package"){
    	def mavenHome = tool name: 'maven-3', type: 'maven'
    	echo "maven home: ${mavenHome}"
    	def mavenCmd = "${mavenHome}/bin/mvn"
		echo "maven cmd: ${mavenCmd}"
        sh "${mavenCmd} clean package"
    }

}
